using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using UnityEngine.SceneManagement;
using UnityEditor.SceneManagement;
[InitializeOnLoad] public static class ArenaFlagSession {
 const string D="C:/Users/Legion/.codex/visualizations/2026/09/26/01a0dc8c-e566-7551-ab70-aaba314fcea0/arena-flags/";
 const string S="Assets/Scenes/Island1_BossArea_Harbor.unity";
 const string A="Assets/Art/Environment/Harbor/Harbor.glb";
 const string N="Harbor - fitted dock instance";
 static ArenaFlagSession(){EditorApplication.update+=Tick;}
 [Serializable] public class Cmd {public string op,file;public Vector3 position,target;public float yaw,scale=1,y,verticalScale=1;public bool ortho;public float size=60;}
 static void Tick(){if(EditorApplication.isCompiling||EditorApplication.isUpdating||!File.Exists(D+"command.json"))return;var c=JsonUtility.FromJson<Cmd>(File.ReadAllText(D+"command.json"));File.Delete(D+"command.json");try{if(SceneManager.GetActiveScene().path!=S)throw new Exception("Wrong scene");if(c.op=="survey")FlagSurvey();if(c.op=="housesurvey")HouseSurvey();if(c.op=="housefix")HouseFix();if(c.op=="houseverify")HouseVerify();if(c.op=="preview")Preview();if(c.op=="flags")BuildFlags();if(c.op=="seat")SeatFlags();if(c.op=="groundaudit")GroundAudit();if(c.op=="groundfix")GroundFix();if(c.op=="groundviews")GroundViews();if(c.op=="verifyfoundations")VerifyFoundations();if(c.op=="refinefoundations")RefineFoundations();if(c.op=="place")Place(c);if(c.op=="render")Render(c);if(c.op=="audit")Audit();if(c.op=="refresh")AssetDatabase.Refresh();if(c.op=="reload")EditorSceneManager.OpenScene(S,OpenSceneMode.Single);if(c.op=="save")EditorSceneManager.SaveScene(SceneManager.GetActiveScene());File.WriteAllText(D+"done.txt",c.op+" OK "+DateTime.Now);}catch(Exception e){File.WriteAllText(D+"error.txt",e.ToString());Debug.LogException(e);}}
 static Bounds B(GameObject g){var rr=g.GetComponentsInChildren<Renderer>(true);if(rr.Length==0)return new Bounds(g.transform.position,Vector3.zero);var b=rr[0].bounds;foreach(var r in rr)b.Encapsulate(r.bounds);return b;}
 static Terrain T(){return UnityEngine.Object.FindObjectsByType<Terrain>(FindObjectsInactive.Include).Single(t=>t.name=="Boss_Area/Harbor"&&t.gameObject.scene.path==S);}
 static float H(float x,float z){var t=T();return t.SampleHeight(new Vector3(x,0,z))+t.transform.position.y;}
 [Serializable] class SurveyData{public Vector3 tilePosition,tileSize,modelSize,modelCenter,modelRootScale,modelRootRotation;public float[] heights;public string[] meshes,materials;public bool dirty;}
 static void Survey(){var t=T();var p=AssetDatabase.LoadAssetAtPath<GameObject>(A);if(!p)throw new Exception("Harbor import has no GameObject");var b=B(p);var d=new SurveyData{tilePosition=t.transform.position,tileSize=t.terrainData.size,modelSize=b.size,modelCenter=b.center,modelRootScale=p.transform.localScale,modelRootRotation=p.transform.eulerAngles,heights=new float[65*65],meshes=p.GetComponentsInChildren<MeshFilter>(true).Select(f=>f.name+" vertices="+f.sharedMesh.vertexCount+" bounds="+f.sharedMesh.bounds).ToArray(),materials=p.GetComponentsInChildren<Renderer>(true).SelectMany(r=>r.sharedMaterials).Select(m=>m.name+" / "+m.shader.name+" supported="+m.shader.isSupported).ToArray(),dirty=SceneManager.GetActiveScene().isDirty};for(int z=0;z<65;z++)for(int x=0;x<65;x++)d.heights[z*65+x]=H(d.tilePosition.x+d.tileSize.x*x/64,d.tilePosition.z+d.tileSize.z*z/64);File.WriteAllText(D+"survey.json",JsonUtility.ToJson(d,true));}
 static void Preview(){var p=AssetDatabase.LoadAssetAtPath<GameObject>(A);var g=UnityEngine.Object.Instantiate(p);g.hideFlags=HideFlags.HideAndDontSave;g.transform.position=new Vector3(3000,0,3000);g.transform.localScale=Vector3.one*.025f;var b=B(g);File.WriteAllText(D+"model-bounds.txt",b.ToString());int i=0;foreach(var v in new[]{new Vector3(1,1.3f,1),new Vector3(-1,.8f,1),new Vector3(1,.8f,-1),new Vector3(0,2.3f,.001f)}){Render(new Cmd{position=b.center+v*45,target=b.center,file="model-"+(i++)+".png"});}UnityEngine.Object.DestroyImmediate(g);}
 static void Render(Cmd c){var cg=new GameObject("Harbor inspection camera"){hideFlags=HideFlags.HideAndDontSave};var cam=cg.AddComponent<Camera>();cam.transform.position=c.position;cam.transform.LookAt(c.target);cam.fieldOfView=50;cam.nearClipPlane=.1f;cam.farClipPlane=600;cam.useOcclusionCulling=false;cam.clearFlags=CameraClearFlags.Skybox;cam.orthographic=c.ortho;cam.orthographicSize=c.size;var lods=UnityEngine.Object.FindObjectsByType<LODGroup>();foreach(var l in lods)l.ForceLOD(0);var rt=new RenderTexture(1400,1000,24);cam.targetTexture=rt;cam.Render();var prior=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(1400,1000,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1400,1000),0,0);tex.Apply();File.WriteAllBytes(D+c.file,tex.EncodeToPNG());RenderTexture.active=prior;cam.targetTexture=null;UnityEngine.Object.DestroyImmediate(tex);UnityEngine.Object.DestroyImmediate(rt);UnityEngine.Object.DestroyImmediate(cg);foreach(var l in lods)l.ForceLOD(-1);}
 static void Place(Cmd c){var t=T();var g=GameObject.Find(N);if(!g){g=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(A));g.name=N;g.transform.SetParent(t.transform,true);Undo.RegisterCreatedObjectUndo(g,"Place Harbor scene instance");}Undo.RecordObject(g.transform,"Fit Harbor model");g.transform.SetPositionAndRotation(Vector3.zero,Quaternion.Euler(0,c.yaw,0)*AssetDatabase.LoadAssetAtPath<GameObject>(A).transform.rotation);g.transform.localScale=new Vector3(c.scale,c.scale,c.scale*c.verticalScale);var b=B(g);g.transform.position+=new Vector3(c.position.x-b.center.x,c.y-b.min.y,c.position.z-b.center.z);b=B(g);var p=t.transform.position;var sz=t.terrainData.size;if(b.min.x<p.x||b.max.x>p.x+sz.x||b.min.z<p.z||b.max.z>p.z+sz.z)throw new Exception("Model exceeds Harbor tile: "+b);PrefabUtility.RecordPrefabInstancePropertyModifications(g.transform);PrefabUtility.RecordPrefabInstancePropertyModifications(g);File.WriteAllText(D+"placement.json",JsonUtility.ToJson(c,true));File.WriteAllText(D+"placed-bounds.txt",b.ToString());EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());}
 static void Audit(){var g=GameObject.Find(N);var t=T();var b=B(g);var sb=new System.Text.StringBuilder();sb.AppendLine("Instance bounds "+b);sb.AppendLine("Transform "+g.transform.position+" yaw="+g.transform.eulerAngles.y+" scale="+g.transform.localScale);sb.AppendLine("Prefab connected: "+PrefabUtility.GetPrefabAssetPathOfNearestInstanceRoot(g));sb.AppendLine("Collider count: "+g.GetComponentsInChildren<Collider>().Length);sb.AppendLine("Boss Arena root: "+GameObject.Find("SUN TEMPLE - Sanctuary of the Tides").transform.position);foreach(var f in g.GetComponentsInChildren<MeshFilter>()){var v=f.sharedMesh.vertices.Select(p=>f.transform.TransformPoint(p)).ToArray();File.WriteAllText(D+f.name+"-vertices.csv",string.Join("\n",v.Select(p=>p.x+","+p.y+","+p.z+","+H(p.x,p.z))));}File.WriteAllText(D+"audit.txt",sb.ToString());}
 static void FlagSurvey(){var root=GameObject.Find("SUN TEMPLE - Sanctuary of the Tides");var sb=new System.Text.StringBuilder();sb.AppendLine("Scene dirty: "+SceneManager.GetActiveScene().isDirty);foreach(var tr in root.GetComponentsInChildren<Transform>(true)){if(tr.parent==root.transform||tr.parent.parent==root.transform){sb.AppendLine(tr.name+" pos="+tr.position+" rot="+tr.eulerAngles+" bounds="+B(tr.gameObject));}}File.WriteAllText(D+"arena-survey.txt",sb.ToString());} const string FF="Assets/Art/Environment/ArenaPirateFlags/";
 static void BuildFlags(){
  if(GameObject.Find("10 - Pirate flags"))throw new Exception("Flag group already exists; inspect before duplicating");
  var importer=(TextureImporter)AssetImporter.GetAtPath(FF+"JollyRoger.png");importer.textureType=TextureImporterType.Default;importer.wrapMode=TextureWrapMode.Clamp;importer.maxTextureSize=2048;importer.anisoLevel=4;importer.SaveAndReimport();
  var cloth=new Material(Shader.Find("Universal Render Pipeline/Lit")){name="Weathered Jolly Roger cloth"};cloth.SetTexture("_BaseMap",AssetDatabase.LoadAssetAtPath<Texture2D>(FF+"JollyRoger.png"));cloth.SetFloat("_Smoothness",.08f);cloth.SetFloat("_Cull",0);cloth.doubleSidedGI=true;AssetDatabase.CreateAsset(cloth,FF+"JollyRogerCloth.mat");
  var pole=new Material(Shader.Find("Universal Render Pipeline/Lit")){name="Dark weathered flagstaff"};pole.SetTexture("_BaseMap",AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Art/ship/Wood/Wood066_2K-PNG_Color.png"));pole.SetColor("_BaseColor",new Color(.34f,.27f,.20f));pole.SetFloat("_Smoothness",.19f);AssetDatabase.CreateAsset(pole,FF+"FlagstaffWood.mat");
  var iron=new Material(Shader.Find("Universal Render Pipeline/Lit")){name="Flagstaff iron bindings"};iron.SetColor("_BaseColor",new Color(.12f,.13f,.13f));iron.SetFloat("_Metallic",.7f);iron.SetFloat("_Smoothness",.28f);AssetDatabase.CreateAsset(iron,FF+"FlagstaffIron.mat");
  var mesh=new Mesh(){name="Wind-shaped frayed pirate cloth"};var v=new List<Vector3>();var uv=new List<Vector2>();var tr=new List<int>();int nx=36,ny=24;
  for(int y=0;y<=ny;y++)for(int x=0;x<=nx;x++){float u=(float)x/nx,w=(float)y/ny;float notch=u>.91f?(Mathf.Pow((u-.91f)/.09f,2)*(.09f+.04f*Mathf.Sin(w*41))):0;float px=u*4.2f-notch;float py=w*2.8f-.13f*u*u+(1-w)*u*.05f*Mathf.Sin(u*43);float pz=u*(.22f*Mathf.Sin(u*8-w*1.2f)+.06f*Mathf.Sin(u*18+w*2));v.Add(new Vector3(px,py,pz));uv.Add(new Vector2(u,w));}
  for(int y=0;y<ny;y++)for(int x=0;x<nx;x++){int a=y*(nx+1)+x,b=a+1,c=a+nx+1,d=c+1;tr.AddRange(new[]{a,b,c,b,d,c});}mesh.SetVertices(v);mesh.SetUVs(0,uv);mesh.SetTriangles(tr,0);mesh.RecalculateNormals();mesh.RecalculateTangents();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,FF+"PirateCloth.asset");
  var template=new GameObject("Pirate Flag - Jolly Roger");
  Part(template,"Timber flagstaff",PrimitiveType.Cylinder,new Vector3(0,3.65f,0),new Vector3(.14f,3.65f,.14f),pole);
  Part(template,"Iron foot socket",PrimitiveType.Cylinder,new Vector3(0,.25f,0),new Vector3(.23f,.27f,.23f),iron);
  foreach(float h in new[]{.8f,3.9f,6.85f})Part(template,"Iron binding",PrimitiveType.Cylinder,new Vector3(0,h,0),new Vector3(.18f,.045f,.18f),iron);
  Part(template,"Mast finial",PrimitiveType.Sphere,new Vector3(0,7.36f,0),Vector3.one*.24f,iron);
  var flag=new GameObject("Skull and crossbones cloth",typeof(MeshFilter),typeof(MeshRenderer));flag.transform.SetParent(template.transform,false);flag.transform.localPosition=new Vector3(.09f,4.08f,0);flag.GetComponent<MeshFilter>().sharedMesh=mesh;flag.GetComponent<MeshRenderer>().sharedMaterial=cloth;
  var prefab=PrefabUtility.SaveAsPrefabAsset(template,FF+"PirateFlag.prefab");UnityEngine.Object.DestroyImmediate(template);
  var arena=GameObject.Find("SUN TEMPLE - Sanctuary of the Tides");var root=new GameObject("10 - Pirate flags");root.transform.SetParent(arena.transform,false);Undo.RegisterCreatedObjectUndo(root,"Decorate Boss Arena with pirate flags");
  Flag(prefab,root,"Western gate - south watchtower",new Vector3(173.5f,23.7f,188.5f),90,.8f);
  Flag(prefab,root,"Western gate - north watchtower",new Vector3(173.5f,22.5f,210.3f),90,.8f);
  Flag(prefab,root,"Sanctuary steps - west standard",new Vector3(236,14.34f,134.3f),0,1);
  Flag(prefab,root,"Sanctuary steps - east standard",new Vector3(261.2f,14.34f,134.3f),0,1);
  Flag(prefab,root,"Harbor gateway - west standard",new Vector3(239,17.55f,202),0,.85f);
  Flag(prefab,root,"Harbor gateway - east standard",new Vector3(262,16.85f,202),0,.85f);
  AssetDatabase.SaveAssets();EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());
  File.WriteAllText(D+"flags.txt",string.Join("\n",root.GetComponentsInChildren<Transform>().Where(t=>t.parent==root.transform).Select(t=>t.name+" "+t.position+" bounds "+B(t.gameObject))));
 }
 static void Part(GameObject parent,string name,PrimitiveType type,Vector3 p,Vector3 s,Material mat){var g=GameObject.CreatePrimitive(type);g.name=name;UnityEngine.Object.DestroyImmediate(g.GetComponent<Collider>());g.transform.SetParent(parent.transform,false);g.transform.localPosition=p;g.transform.localScale=s;g.GetComponent<Renderer>().sharedMaterial=mat;}
 static void Flag(GameObject prefab,GameObject parent,string name,Vector3 pos,float yaw,float scale){var g=(GameObject)PrefabUtility.InstantiatePrefab(prefab);g.name=name;g.transform.SetParent(parent.transform,false);g.transform.position=pos;g.transform.rotation=Quaternion.Euler(0,yaw,0);g.transform.localScale=Vector3.one*scale;PrefabUtility.RecordPrefabInstancePropertyModifications(g);PrefabUtility.RecordPrefabInstancePropertyModifications(g.transform);var b=B(g);var terrains=UnityEngine.Object.FindObjectsByType<Terrain>().Where(t=>t.name=="Boss_Area").ToArray();foreach(var p in new[]{b.min,b.max,new Vector3(b.min.x,0,b.max.z),new Vector3(b.max.x,0,b.min.z)})if(!terrains.Any(t=>p.x>=t.transform.position.x&&p.x<=t.transform.position.x+t.terrainData.size.x&&p.z>=t.transform.position.z&&p.z<=t.transform.position.z+t.terrainData.size.z))throw new Exception("Flag outside Boss_Area: "+name);}
 static void SeatFlags(){var west=GameObject.Find("Sanctuary steps - west standard");west.transform.rotation=Quaternion.Euler(0,180,0);PrefabUtility.RecordPrefabInstancePropertyModifications(west.transform);var sb=new System.Text.StringBuilder();foreach(var pair in new[]{new[]{"Western gate - south watchtower","Gatehouse south watchtower"},new[]{"Western gate - north watchtower","Gatehouse north broken watchtower"},new[]{"Harbor gateway - west standard","Harbor gate west pier"},new[]{"Harbor gateway - east standard","Harbor gate east pier"}}){var flag=GameObject.Find(pair[0]);var support=GameObject.Find(pair[1]);var p=flag.transform.position;Physics.SyncTransforms();var hits=Physics.RaycastAll(new Ray(new Vector3(p.x,100,p.z),Vector3.down),150).Where(h=>h.collider.transform.IsChildOf(support.transform)).OrderBy(h=>h.distance).ToArray();sb.AppendLine(pair[0]+" hits="+hits.Length);if(hits.Length>0){p.y=hits[0].point.y-.18f;flag.transform.position=p;PrefabUtility.RecordPrefabInstancePropertyModifications(flag.transform);sb.AppendLine("Placed on "+hits[0].collider.name+" at "+p);}foreach(var r in support.GetComponentsInChildren<Renderer>())if(r.enabled)sb.AppendLine("visible "+r.name+" "+r.bounds);}EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());File.WriteAllText(D+"seating.txt",sb.ToString());} const string GD="C:/Users/Legion/.codex/visualizations/2026/09/26/01a0dc8c-e566-7551-ab70-aaba314fcea0/arena-grounding/";
 static Terrain[] BossTiles(){return UnityEngine.Object.FindObjectsByType<Terrain>(FindObjectsInactive.Include).Where(t=>t.name=="Boss_Area"&&t.gameObject.scene.path==S).ToArray();}
 static float GH(float x,float z){foreach(var t in BossTiles()){var p=t.transform.position;var sz=t.terrainData.size;if(x>=p.x-.01f&&x<=p.x+sz.x+.01f&&z>=p.z-.01f&&z<=p.z+sz.z+.01f)return t.SampleHeight(new Vector3(x,0,z))+p.y;}return float.NaN;}
 static List<Vector3> Points(GameObject g){var points=new List<Vector3>();foreach(var f in g.GetComponentsInChildren<MeshFilter>()){var r=f.GetComponent<Renderer>();if(!f.sharedMesh||!r||!r.enabled||r.bounds.size.sqrMagnitude<.4f)continue;foreach(var p in f.sharedMesh.vertices)points.Add(f.transform.TransformPoint(p));}return points;}
 [Serializable] class GroundItem{public string name,group,prefab;public Vector3 position,min,max;public float groundMin,groundMax,maxGap,minGap;public int vertices;public Vector3[] bottom;}
 [Serializable] class GroundReport{public GroundItem[] items;}
 static void GroundAudit(){var root=GameObject.Find("SUN TEMPLE - Sanctuary of the Tides");var items=new List<GroundItem>();foreach(Transform group in root.transform){if(group.name.StartsWith("10")||group.name.StartsWith("11"))continue;foreach(Transform tr in group){var v=Points(tr.gameObject);if(v.Count==0)continue;var b=new Bounds(v[0],Vector3.zero);foreach(var p in v)b.Encapsulate(p);var low=v.Where(p=>p.y<b.min.y+.18f).GroupBy(p=>Mathf.Round(p.x*4)+"_"+Mathf.Round(p.z*4)).Select(a=>a.First()).ToArray();var grounds=low.Select(p=>GH(p.x,p.z)).Where(h=>!float.IsNaN(h)).ToArray();if(grounds.Length==0)continue;items.Add(new GroundItem{name=tr.name,group=group.name,prefab=PrefabUtility.GetPrefabAssetPathOfNearestInstanceRoot(tr.gameObject),position=tr.position,min=b.min,max=b.max,groundMin=grounds.Min(),groundMax=grounds.Max(),maxGap=b.min.y-grounds.Min(),minGap=b.min.y-grounds.Max(),vertices=v.Count,bottom=low});}}
 File.WriteAllText(GD+"audit.json",JsonUtility.ToJson(new GroundReport{items=items.ToArray()},true));File.WriteAllText(GD+"floating-report.txt",string.Join("\n",items.OrderByDescending(a=>a.maxGap).Select(a=>a.name+" base="+a.min.y.ToString("F2")+" gaps="+a.minGap.ToString("F2")+".."+a.maxGap.ToString("F2")+" bounds="+a.min+".."+a.max)));} const string GF="Assets/Art/Environment/ArenaFoundations/";
 static float Cross2(Vector2 a,Vector2 b,Vector2 c){return (b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);}
 static List<Vector2> Hull(IEnumerable<Vector3> pts){var q=pts.Select(p=>new Vector2(p.x,p.z)).Distinct().OrderBy(p=>p.x).ThenBy(p=>p.y).ToList();var h=new List<Vector2>();foreach(var p in q){while(h.Count>=2&&Cross2(h[h.Count-2],h[h.Count-1],p)<=.0001f)h.RemoveAt(h.Count-1);h.Add(p);}int n=h.Count;for(int i=q.Count-2;i>=0;i--){while(h.Count>n&&Cross2(h[h.Count-2],h[h.Count-1],q[i])<=.0001f)h.RemoveAt(h.Count-1);h.Add(q[i]);}if(h.Count>1)h.RemoveAt(h.Count-1);return h;}
 static List<Vector2> RectP(float x1,float z1,float x2,float z2){return new List<Vector2>{new Vector2(x1,z1),new Vector2(x2,z1),new Vector2(x2,z2),new Vector2(x1,z2)};}
 static Material FoundationMat(){var m=AssetDatabase.LoadAssetAtPath<Material>(GF+"AgedStoneFootings.mat");if(!m){m=new Material(Shader.Find("Universal Render Pipeline/Lit"));m.name="Aged stone temple foundations";m.SetTexture("_BaseMap",AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Sun_Temple/Content/Textures/stones_rough_A.tif"));m.SetTexture("_BumpMap",AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Sun_Temple/Content/Textures/stones_rough_N.tiff"));m.EnableKeyword("_NORMALMAP");m.SetFloat("_BumpScale",.55f);m.SetFloat("_Smoothness",.16f);m.SetColor("_BaseColor",new Color(.9f,.88f,.82f));AssetDatabase.CreateAsset(m,GF+"AgedStoneFootings.mat");}return m;}
 static void Footing(GameObject root,string name,List<Vector2> shape,float top,float expand){if(shape.Count<3)throw new Exception("No footprint "+name);var center=shape.Aggregate(Vector2.zero,(a,b)=>a+b)/shape.Count;shape=shape.Select(p=>p+(p-center).normalized*expand).ToList();var verts=new List<Vector3>();var uv=new List<Vector2>();var tris=new List<int>();float distance=0;for(int i=0;i<shape.Count;i++){var a=shape[i];var b=shape[(i+1)%shape.Count];float len=Vector2.Distance(a,b);int steps=Mathf.CeilToInt(len/.65f);for(int k=0;k<steps;k++){var p=Vector2.Lerp(a,b,(float)k/steps);var q=Vector2.Lerp(a,b,(float)(k+1)/steps);float hp=GH(p.x,p.y),hq=GH(q.x,q.y);if(float.IsNaN(hp)||float.IsNaN(hq))throw new Exception("Footing outside Boss_Area "+name);float yp=Mathf.Min(top-.15f,hp-.38f),yq=Mathf.Min(top-.15f,hq-.38f);int j=verts.Count;verts.AddRange(new[]{new Vector3(p.x,yp,p.y),new Vector3(p.x,top,p.y),new Vector3(q.x,top,q.y),new Vector3(q.x,yq,q.y)});float u=distance+len*k/steps,w=distance+len*(k+1)/steps;uv.AddRange(new[]{new Vector2(u/3,yp/3),new Vector2(u/3,top/3),new Vector2(w/3,top/3),new Vector2(w/3,yq/3)});tris.AddRange(new[]{j,j+1,j+2,j,j+2,j+3});}distance+=len;}
 int ci=verts.Count;verts.Add(new Vector3(center.x,top,center.y));uv.Add(center/3);foreach(var p in shape){verts.Add(new Vector3(p.x,top,p.y));uv.Add(p/3);}for(int i=0;i<shape.Count;i++)tris.AddRange(new[]{ci,ci+1+(i+1)%shape.Count,ci+1+i});var mesh=new Mesh(){name=name};mesh.SetVertices(verts);mesh.SetUVs(0,uv);mesh.SetTriangles(tris,0);mesh.RecalculateNormals();mesh.RecalculateTangents();mesh.RecalculateBounds();string asset=GF+name.Replace(" ","_")+".asset";AssetDatabase.CreateAsset(mesh,asset);var go=new GameObject(name,typeof(MeshFilter),typeof(MeshRenderer),typeof(MeshCollider));go.transform.SetParent(root.transform,false);go.transform.position=Vector3.zero;go.GetComponent<MeshFilter>().sharedMesh=mesh;go.GetComponent<MeshRenderer>().sharedMaterial=FoundationMat();go.GetComponent<MeshCollider>().sharedMesh=mesh;go.isStatic=true;}
 static void GroundFix(){var arena=GameObject.Find("SUN TEMPLE - Sanctuary of the Tides");if(GameObject.Find("11 - Terrain-fitted foundations"))throw new Exception("Grounding already exists; inspect first");var report=JsonUtility.FromJson<GroundReport>(File.ReadAllText(GD+"audit.json"));var root=new GameObject("11 - Terrain-fitted foundations");root.transform.SetParent(arena.transform,false);Undo.RegisterCreatedObjectUndo(root,"Ground Boss Arena architecture");
 var temple=report.items.Single(i=>i.name.StartsWith("Temple of the Tides"));Footing(root,"Sanctuary continuous stone podium",Hull(temple.bottom),temple.min.y+.045f,.17f);
 Footing(root,"Sanctuary terrace foundation",RectP(233.91f,131.10f,266.10f,136.81f),13.70f,.015f);
 Footing(root,"Staircase foundation",RectP(242.55f,136.47f,257.53f,140.36f),11.55f,.025f);
 Footing(root,"East arcade continuous retaining footing",RectP(269.55f,127.40f,270.45f,147.9f),10.145f,.065f);
 foreach(var item in report.items.Where(i=>new[]{"West cloister bay 4","West cloister bay 5","East cloister bay 4","East cloister turning pavilion","Outer west low boundary 1","Outer west low boundary 3","Exposed east cloister arch","East breached wall stump"}.Contains(i.name)))Footing(root,item.name+" stone footing",Hull(item.bottom),item.min.y+.045f,.07f);
 Physics.SyncTransforms();var log=new System.Text.StringBuilder();foreach(var item in report.items.Where(i=>i.name.StartsWith("Ledge growth in ruined bay")||(i.group.StartsWith("07")&&i.minGap>.04f))){var g=GameObject.Find(item.name);if(!g)continue;float support=GH(item.position.x,item.position.z);foreach(var hit in Physics.RaycastAll(new Vector3(item.position.x,item.min.y+.08f,item.position.z),Vector3.down,30)){if(hit.collider.transform.IsChildOf(g.transform)||hit.collider is TerrainCollider)continue;var rootTr=hit.collider.transform;bool foliage=false;while(rootTr&&rootTr!=arena.transform){if(rootTr.name.StartsWith("08 -")){foliage=true;break;}rootTr=rootTr.parent;}if(!foliage&&hit.point.y<=item.min.y+.08f)support=Mathf.Max(support,hit.point.y);}float delta=support-item.min.y-.02f;if(delta<-.08f){Undo.RecordObject(g.transform,"Seat floating detail");g.transform.position+=Vector3.up*delta;PrefabUtility.RecordPrefabInstancePropertyModifications(g.transform);log.AppendLine(item.name+" lowered "+(-delta).ToString("F3")+"m onto "+support);}}
 AssetDatabase.SaveAssets();EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());File.WriteAllText(GD+"placement-corrections.txt",log.ToString());File.WriteAllText(GD+"foundation-count.txt",root.transform.childCount+" terrain-fitted stone foundations; terrain heights unchanged.");}
 static void GroundViews(){Render(new Cmd{position=new Vector3(280,11,119),target=new Vector3(253,13,117),file="grounding-east.png"});Render(new Cmd{position=new Vector3(275,9,144),target=new Vector3(255,12,131),file="grounding-arcade.png"});Render(new Cmd{position=new Vector3(251,12,81),target=new Vector3(250,15,104),file="grounding-rear.png"});Render(new Cmd{position=new Vector3(244,16,157),target=new Vector3(249,15,132),file="grounding-steps.png"});}
 static GameObject[] HouseParts(){return Enumerable.Range(1,5).Select(i=>GameObject.Find("West cloister bay "+i)).ToArray();}
 static void HouseFix(){
 if(GameObject.Find("West cloister continuous raised foundation"))throw new Exception("House already repaired");
 var parts=HouseParts();var pts=parts.SelectMany(g=>Points(g)).ToArray();float oldBase=pts.Min(p=>p.y);float high=-1000;for(float x=190.2f;x<=197.8f;x+=.1f)for(float z=148.9f;z<=189.1f;z+=.1f)high=Mathf.Max(high,GH(x,z));float top=high+.10f,delta=top-oldBase;
 Undo.SetCurrentGroupName("Unbury west cloister building");foreach(var g in parts){Undo.RecordObject(g.transform,"Raise joined house section");g.transform.position+=Vector3.up*delta;PrefabUtility.RecordPrefabInstancePropertyModifications(g.transform);}
 foreach(var name in new[]{"Ledge growth in ruined bay 1","Ledge growth in ruined bay 2"}){var g=GameObject.Find(name);Undo.RecordObject(g.transform,"Keep ledge growth on house");g.transform.position+=Vector3.up*delta;PrefabUtility.RecordPrefabInstancePropertyModifications(g.transform);}
 var root=GameObject.Find("11 - Terrain-fitted foundations");var low=pts.Where(p=>p.y<oldBase+.18f);Footing(root,"West cloister continuous raised foundation",Hull(low),top+.035f,.15f);
 foreach(var name in new[]{"West cloister bay 4 stone footing","West cloister bay 5 stone footing"}){var g=GameObject.Find(name);Undo.RecordObject(g,"Superseded by continuous foundation");g.SetActive(false);}
 var log=new System.Text.StringBuilder();log.AppendLine("Raised all five sections by "+delta+" metres; base="+top+"; maximum original terrain="+high);
 for(int i=0;i<5;i++){float z=153.115f+i*8;BuildHouseSteps(root,i+1,z,top,log);}
 AssetDatabase.SaveAssets();EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());File.WriteAllText(HD+"repair.txt",log.ToString());HouseVerify();
 }
 static void BuildHouseSteps(GameObject parent,int number,float z,float top,System.Text.StringBuilder log){
 var vv=new List<Vector3>();var uv=new List<Vector2>();var tt=new List<int>();Action<Vector3,Vector3,Vector3,Vector3> quad=(a,b,c,d)=>{int j=vv.Count;vv.AddRange(new[]{a,b,c,d});var n=Vector3.Cross(b-a,c-a).normalized;foreach(var p in new[]{a,b,c,d})uv.Add(Mathf.Abs(n.y)>.5f?new Vector2(p.x,p.z)/3:Mathf.Abs(n.x)>.5f?new Vector2(p.z,p.y)/3:new Vector2(p.x,p.y)/3);tt.AddRange(new[]{j,j+1,j+2,j,j+2,j+3});};
 int count=0;float toeGap=0;for(int k=0;k<35;k++){float x=197.66f+k*.34f,x2=x+.342f,z1=z-.95f,z2=z+.95f,h=top-k*.17f;float ground=Mathf.Min(GH(x2,z1),GH(x2,z2));if(k==0&&ground>=h+.15f)break;
 float y1=Mathf.Min(h-.12f,GH(x,z1)-.25f),y2=Mathf.Min(h-.12f,GH(x,z2)-.25f),y3=Mathf.Min(h-.12f,GH(x2,z2)-.25f),y4=Mathf.Min(h-.12f,GH(x2,z1)-.25f);
 var a=new Vector3(x,h,z1);var b=new Vector3(x,h,z2);var c=new Vector3(x2,h,z2);var d=new Vector3(x2,h,z1);quad(a,b,c,d);quad(new Vector3(x,y1,z1),a,d,new Vector3(x2,y4,z1));quad(new Vector3(x2,y3,z2),c,b,new Vector3(x,y2,z2));quad(new Vector3(x2,y4,z1),d,c,new Vector3(x2,y3,z2));quad(new Vector3(x,y2,z2),b,a,new Vector3(x,y1,z1));count++;toeGap=h-ground;if(toeGap<=.18f)break;}
 if(count==0)return;var mesh=new Mesh{name="West cloister entrance steps "+number};mesh.SetVertices(vv);mesh.SetUVs(0,uv);mesh.SetTriangles(tt,0);mesh.RecalculateNormals();mesh.RecalculateTangents();mesh.RecalculateBounds();AssetDatabase.CreateAsset(mesh,GF+"West_cloister_entrance_steps_"+number+".asset");var go=new GameObject(mesh.name,typeof(MeshFilter),typeof(MeshRenderer),typeof(MeshCollider));go.transform.SetParent(parent.transform,false);go.transform.position=Vector3.zero;go.GetComponent<MeshFilter>().sharedMesh=mesh;go.GetComponent<MeshRenderer>().sharedMaterial=FoundationMat();go.GetComponent<MeshCollider>().sharedMesh=mesh;go.isStatic=true;log.AppendLine("Entrance "+number+": "+count+" treads; last tread terrain gap="+toeGap);}
 static void HouseVerify(){Physics.SyncTransforms();var root=GameObject.Find("West cloister continuous raised foundation");var collider=root.GetComponent<MeshCollider>();var log=new System.Text.StringBuilder();int count=0,bad=0;foreach(var g in HouseParts()){var pts=Points(g);float min=pts.Min(p=>p.y);float gap=0;foreach(var p in pts.Where(p=>p.y<min+.18f)){RaycastHit hit;float support=GH(p.x,p.z);if(collider.Raycast(new Ray(new Vector3(p.x,100,p.z),Vector3.down),out hit,150))support=Mathf.Max(support,hit.point.y);gap=Mathf.Max(gap,min-support);count++;if(min-support>.1f)bad++;}log.AppendLine(g.name+" base="+min+" maximum support gap="+gap);}float high=-1000;for(float x=190.2f;x<=197.8f;x+=.1f)for(float z=148.9f;z<=189.1f;z+=.1f)high=Mathf.Max(high,GH(x,z));log.AppendLine("Maximum underlying terrain="+high+"; "+count+" base vertex checks; unsupported="+bad);File.WriteAllText(HD+"verification.txt",log.ToString());}
 const string HD="C:/Users/Legion/.codex/visualizations/2026/09/26/01a0dc8c-e566-7551-ab70-aaba314fcea0/arena-house/";
 static void HouseSurvey(){var sb=new System.Text.StringBuilder();sb.AppendLine("Dirty before save: "+SceneManager.GetActiveScene().isDirty);EditorSceneManager.SaveScene(SceneManager.GetActiveScene());File.Copy(S,HD+"scene-before.unity",true);var view=SceneView.lastActiveSceneView;if(view){sb.AppendLine("Scene camera "+view.camera.transform.position+" rotation "+view.camera.transform.eulerAngles);Render(new Cmd{position=view.camera.transform.position,target=view.camera.transform.position+view.camera.transform.forward*30,file="house-current-view.png"});}foreach(var n in new[]{"West cloister bay 1","West cloister bay 2","West cloister bay 3","West cloister bay 4","West cloister bay 5"}){var g=GameObject.Find(n);var vv=Points(g);var b=new Bounds(vv[0],Vector3.zero);foreach(var p in vv)b.Encapsulate(p);float lo=1000,hi=-1000;for(float x=b.min.x;x<=b.max.x;x+=.25f)for(float z=b.min.z;z<=b.max.z;z+=.25f){float h=GH(x,z);lo=Mathf.Min(lo,h);hi=Mathf.Max(hi,h);}sb.AppendLine(n+" root "+g.transform.position+" bounds "+b+" terrain "+lo+".."+hi);foreach(var f in g.GetComponentsInChildren<MeshFilter>()){var r=f.GetComponent<Renderer>();if(r&&r.enabled)sb.AppendLine("mesh "+f.name+" "+r.bounds);}}File.WriteAllText(HD+"survey.txt",sb.ToString());}
 static void RefineFoundations(){foreach(var name in new[]{"Sanctuary terrace foundation","Staircase foundation"}){var g=GameObject.Find(name);var m=g.GetComponent<MeshFilter>().sharedMesh;var b=m.bounds;var vv=m.vertices;float add=name.StartsWith("Sanctuary")?.24f:.34f;for(int i=0;i<vv.Length;i++){var p=vv[i];p.x=b.center.x+(p.x-b.center.x)*(b.size.x+add)/b.size.x;p.z=b.center.z+(p.z-b.center.z)*(b.size.z+add)/b.size.z;if(p.y<b.max.y-.1f)p.y=Mathf.Min(b.max.y-.15f,GH(p.x,p.z)-.38f);vv[i]=p;}m.vertices=vv;m.RecalculateNormals();m.RecalculateTangents();m.RecalculateBounds();g.GetComponent<MeshCollider>().sharedMesh=null;g.GetComponent<MeshCollider>().sharedMesh=m;EditorUtility.SetDirty(m);}AssetDatabase.SaveAssets();Physics.SyncTransforms();VerifyFoundations();}
 static void VerifyFoundations(){
 var root=GameObject.Find("11 - Terrain-fitted foundations");if(!root)throw new Exception("Missing foundations");Physics.SyncTransforms();var cc=root.GetComponentsInChildren<MeshCollider>();var report=JsonUtility.FromJson<GroundReport>(File.ReadAllText(GD+"audit.json"));var log=new System.Text.StringBuilder();int tested=0,fail=0;
 foreach(var it in report.items.Where(i=>i.name.StartsWith("Temple of")||i.name.StartsWith("Temple apron")||i.name.StartsWith("Broad temple ascent")||i.name.StartsWith("Terrace front")||i.name.StartsWith("Sanctuary east arcade")||new[]{"West cloister bay 4","West cloister bay 5","East cloister bay 4","East cloister turning pavilion","Outer west low boundary 1","Outer west low boundary 3","Exposed east cloister arch","East breached wall stump"}.Contains(i.name))){int bad=0;float max=0;foreach(var p in it.bottom){float support=GH(p.x,p.z);foreach(var c in cc){RaycastHit h;if(c.Raycast(new Ray(new Vector3(p.x,100,p.z),Vector3.down),out h,150))support=Mathf.Max(support,h.point.y);}float gap=it.min.y-support;if(gap>.2f)bad++;max=Mathf.Max(max,gap);tested++;}fail+=bad;log.AppendLine(it.name+": "+it.bottom.Length+" samples, unsupported="+bad+", maxGap="+max.ToString("F3"));}
 foreach(var c in cc){var vv=c.sharedMesh.vertices;int bottoms=0;float highest=float.MinValue;for(int i=0;i<vv.Length;i+=1){var p=c.transform.TransformPoint(vv[i]);if(p.y<c.bounds.max.y-.1f){highest=Mathf.Max(highest,p.y-GH(p.x,p.z));bottoms++;}}log.AppendLine(c.name+": "+bottoms+" skirt samples, max terrain clearance="+highest.ToString("F3"));}
 log.AppendLine("TOTAL "+tested+" architecture foot samples; unsupported (>0.2m): "+fail);File.WriteAllText(GD+"verification.txt",log.ToString());
 }
}








